name: Label Release PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  permissions:
    pull-requests: write
  label_release_pr:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Add label to release PRs
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
